exclude_dirs:
 - .tox
 - .git
 - .mypy_cache
 - .pytest_cache
 - .github
 - venv
 - tests/*


skips:
- B101 # :assert_used
- B309
- B608 # :hardcoded_sql_expressions

assert_used:
  skips: ['*_test.py', 'test_*.py']
