#
# Development tools for ontopia. Run with:
#
#   docker-compose up test
#
version: "3.3"
services:
  test-onto:
    build: .
    volumes:
    - .:/code
    working_dir: /code
    command:
    - /bin/sh
    - -c
    - >-
      pre-commit run -a onto-pyshacl && pre-commit run -a onto-latest
