#
# Development tools for ontopia. Run with:
#
#   docker-compose up test
#
version: "3.3"
services:
  test-onto: &test-base
    build:
      dockerfile: tests/Dockerfile
      context: .
    volumes:
    - .:/code
    working_dir: /code
    command:
    - /bin/sh
    - -c
    - >-
      pre-commit run -a onto-pyshacl && pre-commit run -a onto-latest

  test:
    <<: *test-base
    command: pre-commit run -a

  build:
    <<: *test-base
    command: tox -e build
